### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mathias-von-ottenbreit** [tnagler/kde1d#30]
Hi.
The below code gives the following error:
_Error in fit_kde1d_cpp(x, bw, xmin, xmax, deg) : 
  Error in function boost::math::pdf(const normal_distribution<double>&, double): Random variate x is nan, but must be finite!_

set.seed(2019)
data=rnorm(1000)
data[1:800]=0
test=kde1d(data) #I believe that the error happens in bandwidth selection

Thanks.

Mathias

**Comment by tnagler** [comment]
Hi Matthias, it's fixed in the dev version (`devtools::install_github("tnagler/kde1d", ref = "dev")`). Just so you know, if your data looks like that, you probably shouldn't use a plain kde. A kde assumes that the data comes from a continuous distribution.
