### ISSUE TITLE
The output of `dkde1d` is invisible

### ISSUE THREAD

**Issue by stla** [tnagler/kde1d#50]
Hello,

 Thank you for this package. I've just [blogged](https://laustep.github.io/stlahblog/posts/kde1d.html) about it.

The `dkde1d` returns the expected output but invisibly. This can be fixed by adding `fhat` at the end of the function:

```r
dkde1d <- function(x, obj) {
  x <- prep_eval_arg(x, obj)
  if (length(obj$jitter_info$i_disc) == 1) {
    # for backwards compatibility with rvinecopulib
    # TODO: remove next version
    if (!is.ordered(x))
      x <- ordered(x, obj$jitter_info$levels$x)
    fhat <- dkde1d_cpp(as.numeric(x) - 1, obj)
    f_all <- dkde1d_cpp(seq_along(obj$jitter_info$levels$x) - 1, obj)
    fhat <- fhat / sum(f_all)
  } else {
    fhat <- dkde1d_cpp(x, obj)
  }
  fhat # added by me
}
```

**Comment by tnagler** [comment]
Oh thanks for the nice blog post!

And thanks for notifying me about this (stupid) bug. It's fixed in c02df61.
