### ISSUE TITLE
Error in kde1d() when both xmax and xmin are specified

### ISSUE THREAD

**Issue by rplzzz** [tnagler/kde1d#54]
Trying to fit a density with bounded minimum and maximum support fails with an error in kde1d v. 1.0.3.  Here's an example:
```R
y <- c(0.211735408054665, 92.2377439634642, 93.8867637729738, 94.9404157818761, 
95.7743193039205, 96.5234082606621, 97.2392323357984, 97.946841336973, 
98.6924901425838, 99.6256911783014, 100)

kde1d::kde1d(y, xmin=0, xmax=100)
```
> Error in fit_kde1d_cpp(x = if (is.numeric(x)) x else (as.numeric(x) -  : 
  Error in function boost::math::quantile(const normal_distribution<double>&, double): Probability argument is -0.0027828676326900801, but must be >= 0 and <= 1 !

Specifying either limit on its own works:
```R
kde1d::kde1d(y, xmax=100)
```
> kernel density estimate ('kde1d'), log-quadratic with bounded support (xmax = 100)
```R
kde1d::kde1d(y, xmin=0)
```
> kernel density estimate ('kde1d'), log-quadratic with bounded support (xmin = 0)

Adjusting the upper limit so that the maximum data point is not right on the boundary does not help:
```R
kde1d::kde1d(y, xmin=0, xmax=100.1)
```
> Error in fit_kde1d_cpp(x = if (is.numeric(x)) x else (as.numeric(x) -  : 
  Error in function boost::math::quantile(const normal_distribution<double>&, double): Probability argument is -0.0027899826600290534, but must be >= 0 and <= 1 !

**Comment by tnagler** [comment]
Should be fixed by 33bfd94c5278d12717d0c657d8bf5d4e36a2a93e. You can install the fixed version with:
``` r 
devtools::install_github("tnagler/kde1d@dev")
```
